variables:
  BuildConfiguration: 'Release'
  CI: true
  NODE_VERSION: 16.14.2
  DOTNET_VERSION: 6.0.x

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
    - infrastructure/
pr: [ 'master', 'dev' ]

jobs:
  - job: 'Frontend'
    pool: Default
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NODE_VERSION)'
        inputs:
          versionSpec: $(NODE_VERSION)

      - task: 'Bash@3'
        displayName: 'corepack enable'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'corepack enable'

      - task: 'Bash@3'
        displayName: 'pnpm i'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm i'

      - task: 'Bash@3'
        displayName: 'pnpm run build'
        inputs:
          targetType: 'inline'
          script: 'pnpm --filter=explore-education-statistics-frontend run build'

      - task: 'Bash@3'
        displayName: 'Remove dev dependencies'
        inputs:
          targetType: 'inline'
          script: 'rm -rf ./src/**/node_modules'

      - task: 'Bash@3'
        displayName: 'Install prod dependencies'
        inputs:
          targetType: 'inline'
          script: 'pnpm i --filter=explore-education-statistics-frontend... --prod'

      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: './src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/public-frontend.zip'

      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend'
          targetPath: '$(Build.ArtifactStagingDirectory)'
