trigger:
  paths:
    include:
    - infrastructure/

pr:
  paths:
    include:
    - infrastructure/

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzSKARMTemplateChecker@4
  inputs:
    ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/templates/'
